<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\Post $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="post-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Post',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger',
    'fieldConfig' => [
             'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
             'horizontalCssClasses' => [
                 'label' => 'col-sm-2',
                 #'offset' => 'col-sm-offset-4',
                 'wrapper' => 'col-sm-8',
                 'error' => '',
                 'hint' => '',
             ],
         ],
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute r_sub_category_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'r_sub_category_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\SubCategory::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['r_sub_category_id'])),
    ]
); ?>

<!-- attribute r_user_id -->
			<?= $form->field($model, 'r_user_id')->textInput() ?>

<!-- attribute c_shop_name -->
			<?= $form->field($model, 'c_shop_name')->textInput(['maxlength' => true]) ?>

<!-- attribute c_shop_place -->
			<?= $form->field($model, 'c_shop_place')->textInput(['maxlength' => true]) ?>

<!-- attribute c_price -->
			<?= $form->field($model, 'c_price')->textInput() ?>

<!-- attribute c_duration -->
			<?= $form->field($model, 'c_duration')->textInput() ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('models', 'Post'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('cruds', 'Create') : Yii::t('cruds', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

